"""backend/app/migrations/versions/20261019120000_add_supplychain_tables.py
Revision ID: 20261019120000
Revises: None
Create Date: 2026-10-19 12:00:00

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20261019120000'
 down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sbom',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('content', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_event',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('severity_score', sa.Float(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('anomaly_type', sa.String(length=50), nullable=False),
        sa.Column('severity_score', sa.Float(), nullable=False),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('detected_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apt_simulation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('scenario_name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('parameters', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apt_simulation')
    op.drop_table('anomaly')
    op.drop_table('risk_event')
    op.drop_table('sbom')
    # ### end Alembic commands ###
"""
